### ISSUE TITLE
unity cannot resolving packages!

### ISSUE THREAD

**Issue by JokerJohn** [autocore-ai/MapToolbox#11]
hello，when I  Create my new project in Unity 2018.2
 and add two lines to Packages/manifest.json dependencies，this error was thrown：
![error2名](https://user-images.githubusercontent.com/25702851/60778205-96c9f780-a168-11e9-8c9d-e5ba2341513f.jpg)

**Comment by JokerJohn** [comment]
how can I solve it?

**Comment by MoeLang** [comment]
@JokerJohn Load git url needs [Unity 2019.1](https://store.unity.com/download?ref=personal) or above version, it's an experiment.

**Comment by JokerJohn** [comment]
ok，thank you

**Comment by LinuxCup** [comment]
there was a problem when i fixed 'manifest.json' file.

like this:
Library\PackageCache\com.autocore.map-toolbox@4bc1255ed0587b7ad67b731890c90d53b66bff06\VectorMapTools\DoubleConnectBezier.cs(29,16): error CS0246: The type or namespace name 'PointOctree<>' could not be found (are you missing a using directive or an assembly reference?)Library\PackageCache\com.autocore.map-toolbox@4bc1255ed0587b7ad67b731890c90d53b66bff06\VectorMapTools\Lane.cs(27,16): error CS0246: The type or namespace name 'PointOctree<>' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.autocore.map-toolbox@4bc1255ed0587b7ad67b731890c90d53b66bff06\VectorMapTools\Lane.cs(28,25): error CS0246: The type or namespace name 'PointOctree<>' could not be found (are you missing a using directive or an assembly reference?)Library\PackageCache\com.autocore.map-toolbox@4bc1255ed0587b7ad67b731890c90d53b66bff06\VectorMapTools\Export\VectorMapCollection.cs(28,16): error CS0246: The type or namespace name 'PointOctree<>' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.autocore.map-toolbox@4bc1255ed0587b7ad67b731890c90d53b66bff06\VectorMapTools\Export\VectorMapExtern.cs(66,13): error CS0246: The type or namespace name 'PointOctree<>' could not be found (are you missing a using directive or an assembly reference?)

![捕获](https://user-images.githubusercontent.com/22309810/64149331-3c8f9f00-ce58-11e9-980c-96251eb07a0d.PNG)

**Comment by MoeLang** [comment]
![image](https://user-images.githubusercontent.com/7805397/64149839-9ba1e380-ce59-11e9-9eb5-c38719256a0d.png)
@LinuxCup  Can you find this package?
![image](https://user-images.githubusercontent.com/7805397/64149936-c724ce00-ce59-11e9-8c8d-4a936e2824e2.png)
manifest.json

**Comment by LinuxCup** [comment]
thinks for your resply! my panel is different from yours, but i followed your instructions on the 'manifest.json' file.
![捕获1](https://user-images.githubusercontent.com/22309810/64154018-939a7180-ce62-11e9-864e-bc0ec4630cec.PNG)

![捕获2](https://user-images.githubusercontent.com/22309810/64154036-9b5a1600-ce62-11e9-88d5-42e85961b80f.PNG)

**Comment by LinuxCup** [comment]
i know this tool is used for autoware, is there any other may to make vecotr map? i am very interested in autonomous vehicle

**Comment by MoeLang** [comment]
![image](https://user-images.githubusercontent.com/7805397/64154662-e1fc4000-ce63-11e9-986f-84cd4c333524.png)
@LinuxCup 

Error message caused by this null reference, I guess assembly GUID changed during unity update, It works well in latest unity version (Unity 2019.1.14f1), next update I will use name instead of GUID.

There are many map format can use for autonomous HD map (vector map), such as OpenDRIVE/ Lanelet2(OpenStreetMap format). Autoware use vector map supported by AsiaTech, and they will changing format to lanelet2.

**Comment by LinuxCup** [comment]
@MoeLang
Thanks for your explanation! 
 thank you again.
